#!/bin/bash
#set -e;

HOME=/home/git/.riakcs

# Check if name is specified
if [[ $1 == riakcs:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "/home/git/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

if [[ $APP_EXISTS == false ]]; then
  echo "App must exist before creating RiakCS storage for it"
  exit 1
fi

set_dokku_env() {
  ENV_PATH=$1
  ENV_VAR=$2
  ENV_VAL=$3
  awk '/^export '$ENV_VAR'=/ {print "export '$ENV_VAR'=\"'$ENV_VAL'\""; found=1} !/^export '$ENV_VAR'=/ {print $0} END {if (!found) {print "export '$ENV_VAR'=\"'$ENV_VAL'\"" }}' ${ENV_PATH} > ${ENV_PATH}.new
  mv "${ENV_PATH}.new" ${ENV_PATH}
  rm ${ENV_PATH}.new
}

clear_dokku_env() {
  local ref=$1[@]
  for x in ${!ref}; do
    cat "${APP_PATH}/ENV" | grep -v ${x} > ${APP_PATH}/ENV.new
    mv "${APP_PATH}/ENV.new" $APP_PATH/ENV
    rm "${APP_PATH}/ENV.new"
  done
}

APP_PATH=/home/git/$APP

ADMIN_KEY=`cat /home/git/.riakcs/admin_user.json | grep -E -o '"key_id":"[^\"]+"' | sed -e 's/\"//g' | cut -d : -f 2`
ADMIN_SECRET=`cat /home/git/.riakcs/admin_user.json | grep -E -o '"key_secret":"[^\"]+"' | sed -e 's/\"//g' | cut -d : -f 2`
RIAK_CONTAINER=`docker ps|grep "jeffutter/riakcs:latest"| cut -f 1 -d ' '`
RIAK_PORT=`docker port ${RIAK_CONTAINER} 8080`

cat <<EOF >> $HOME/.s3curl
%awsSecretAccessKeys = (
    admin => {
        id => '${ADMIN_KEY}',
        key => '${ADMIN_SECRET}',
    },
);
EOF
chmod 600 $HOME/.s3curl

case "$1" in
  riakcs:create)
    perl ~/s3-curl/s3curl.pl --id admin --contentType application/json --post -- -s -x localhost:${RIAK_PORT} --data "{\"email\":\"${APP}@${HOSTNAME}\", \"name\":\"${APP}\"}" http://riak-cs.s3.amazonaws.com/user > ~/user_$APP.json
    USER_KEY=`cat ~/user_$APP.json | grep -E -o '"key_id":"[^\"]+"' | sed -e 's/\"//g' | cut -d : -f 2`
    USER_SECRET=`cat ~/user_$APP.json | grep -E -o '"key_secret":"[^\"]+"' | sed -e 's/\"//g' | cut -d : -f 2`

    if [[ ! -f /home/git/$APP/ENV ]]; then
      touch /home/git/$APP/ENV
    fi

    set_dokku_env $APP_PATH/ENV S3_PORT $RIAK_PORT
    set_dokku_env $APP_PATH/ENV S3_KEY $USER_KEY
    set_dokku_env $APP_PATH/ENV S3_SECRET $USER_SECRET

    chown git: $APP_PATH/ENV
    ;;
  riakcs:delete)
    USER_KEY=`cat ~/user_$APP.json | grep -E -o '"key_id":"[^\"]+"' | sed -e 's/\"//g' | cut -d : -f 2`
    perl /home/git/.riakcs/s3-curl/s3curl.pl --id admin --delete -- -s -x localhost:${RIAK_PORT} http://riak-cs.s3.amazonaws.com/user/${USER_KEY}

    if [[ ! -f $APP_PATH/ENV ]]; then
      touch $APP_PATH/ENV
    fi

    VARS=( "S3_KEY" "S3_SECRET" "S3_PORT")
    clear_dokku_env VARS 

    chown git: $APP_PATH/ENV
    ;;
  riakcs:list)
    perl ~/s3-curl/s3curl.pl --id admin -- -s -x localhost:${RIAK_PORT} -H "Accept: application/json" http://s3.amazonaws.com/riak-cs/users
    ;;
  *)
    echo "Command Not Found"
    exit 1
    ;;
esac
cat
