#!/bin/bash
#set -e;

HOME=/home/git/.riakcs

# Check if name is specified
if [[ $1 == riakcs:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "/home/git/$APP" ]]; then
            app_exists=true
        else
            app_exists=false
        fi
    fi
fi

check_exists() {
  if [[ $app_exists == false ]]; then
    echo "App must exist before creating mongodb storage for it"
    exit 1
  fi
}

set_dokku_env() {
  env_path=$1
  env_var=$2
  env_val=$3
  ex -sc "\"g/export ${env_var}=/d|x\"" "$env_path"
  echo "export ${env_var}=\"${env_val}\"" >> "$env_path"
}

clear_dokku_env() {
  local ref=$1[@]
  for x in ${!ref}; do
    ex -sc "g/${env_var}/d" -c "x" "$app_path/ENV"
  done
}

app_path=/home/git/$APP

db_image=jeffutter/riakcs
id=$(docker ps -a | grep "$db_image":latest |  awk '{print $1}')
riak_port=$(docker port ${id} 8080)
riak_ip=$(docker inspect ${id} | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
bucket_name='default'

case "$1" in
  riakcs:create)
    check_exists

    perl ~/s3-curl/s3curl.pl --id admin --contentType application/json --post -- -s -x localhost:${riak_port} --data "{\"email\":\"${APP}@${HOSTNAME}\", \"name\":\"${APP}\"}" http://riak-cs.s3.amazonaws.com/user > ~/user_$APP.json

    user_key=$(cat ~/user_${APP}.json | python -c "import json;import sys;print json.loads(sys.stdin.readline())['key_id']")
    user_secret=$(cat ~/user_${APP}.json | python -c "import json;import sys;print json.loads(sys.stdin.readline())['key_secret']")

    s3curl="${APP} => { id => '${user_key}', key => '${user_secret}',},"

    ex -sc "%s/^);\$/${s3curl});/g" -c "x" ~/.s3curl

    perl ~/s3-curl/s3curl.pl --id ${APP} -- -s -v -x localhost:${riak_port} -X PUT http://${bucket_name}.s3.amazonaws.com/

    if [[ ! -f /home/git/$APP/ENV ]]; then
      touch /home/git/$APP/ENV
    fi

    riak_port=8080
    set_dokku_env $app_path/ENV S3_PROXY_HOST $riak_ip
    set_dokku_env $app_path/ENV S3_PROXY_PORT $riak_port
    set_dokku_env $app_path/ENV AWS_ACCESS_KEY_id $user_key
    set_dokku_env $app_path/ENV AWS_SECRET_ACCESS_KEY $user_secret
    set_dokku_env $app_path/ENV S3_BUCKET_NAME $bucket_name
    set_dokku_env $app_path/ENV S3_ASSET_URL "http://assets.${APP}.${HOSTNAME}/${bucket_name}"
    set_dokku_env $app_path/ENV S3_ENDPOINT 'http://s3.amazonaws.com'

    chown git: $app_path/ENV
    ;;
  riakcs:delete)
    check_exists

    user_key=$(cat ~/user_${APP}.json | python -c "import json;import sys;print json.loads(sys.stdin.readline())['key_id']")
    perl /home/git/.riakcs/s3-curl/s3curl.pl --id admin --delete -- -s -x localhost:${riak_port} http://riak-cs.s3.amazonaws.com/user/${user_key}

    ex -sc "g/${APP} =>/d" -c "x" ~/.s3curl

    if [[ ! -f $app_path/ENV ]]; then
      touch $app_path/ENV
    fi

    VARS=( "AWS_ACCESS_KEY_id" "AWS_SECRET_ACCESS_KEY" "S3_PROXY_PORT" "S3_PROXY_HOST" "S3_BUCKET_NAME" "S3_ASSET_URL" "S3_ENDPOINT")
    clear_dokku_env VARS 

    chown git: $app_path/ENV
    ;;
  riakcs:list)
    perl ~/s3-curl/s3curl.pl --id admin -- -s -x localhost:${riak_port} -H "Accept: application/json" http://s3.amazonaws.com/riak-cs/users
    ;;
  *)
    echo "Command Not Found"
    exit 1
    ;;
esac
cat
