#!/bin/bash
set -e
APP="$1"

if [[ -f "$DOKKU_ROOT/VHOST" ]]; then
  VHOST=$(< "$DOKKU_ROOT/VHOST")
  SUBDOMAIN=${APP/%\.${VHOST}/}
  if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
    hostname="${APP/\//-}"
  else
    hostname="${APP/\//-}.$VHOST"
  fi

  if [[ -f "$DOKKU_ROOT/.riakcs/user_${APP}.json" ]]; then

    db_image="jeffutter/riakcs"
    id=$(docker ps | grep "$db_image":latest |  awk '{print $1}')
    riak_ip=$(docker port ${id} 8080 | awk '{split($0,a,":"); print a[1]}')
    riak_port=$(docker port ${id} 8080 | awk '{split($0,a,":"); print a[2]}')
    if [[ $riak_ip = "0.0.0.0" ]]; then
      riak_ip=localhost
    fi

    if [[ ! -f "$DOKKU_ROOT/$APP/nginx-assets.conf" ]]; then
      touch "$DOKKU_ROOT/$APP/nginx-assets.conf"
    fi

    cat<<EOF > "$DOKKU_ROOT/$APP/nginx-assets.conf"

upstream riak_cs_${APP} {
  server  ${riak_ip}:${riak_port};
}

server {
  listen   80;
  server_name  assets.${hostname};

  location / {
      proxy_set_header Host \$http_host;
      proxy_set_header X-Real-IP \$remote_addr;
      proxy_redirect off;

      proxy_connect_timeout      90;
      proxy_send_timeout         90;
      proxy_read_timeout         90;

      proxy_pass http://riak_cs_${APP};
    }
}
EOF

  fi
fi
